title: Diversity, Inclusion and Leadership in Tech
logo: /img/logo.png
description: This is a reading seminar on issues of diversity and inclusion, focusing on how to take leadership in creating more equitable and just communities in tech. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
